spring:
  jackson:
    serialization:
      indent_output: true
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    ## jpa相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# create：每次运行程序时，都会重新创建表，故而数据会丢失
# create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
# update：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
# validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
# none: 禁用DDL处理

server:
  port: 8182